### ISSUE TITLE
Date picker size

### ISSUE THREAD

**Issue by JonDeG** [Project-Pier/ProjectPier-Core#1]
The resized date picker created with SHA: 53f133e75558c50f9e7712be014d8f9d5c97b9fa in the current master branch is excessively wide. It expands to fill the width of the browser window on the the right edge.
![be4ab112-91ed-11e4-8de0-957e1a75f82d](https://cloud.githubusercontent.com/assets/2878315/5639651/78b0b210-95e8-11e4-8c28-8165728bb362.jpg)

**Comment by Engelbert** [comment]
@JonDeG : I think this is a theme related bug. This  might need moving to the appropriate repo. 
Or will the standard theme be part of the core?
Imo it should be separate, but that might be harder for development of new functions.
What do you think ?

**Comment by JonDeG** [comment]
I believe the 'size' of it is in the core, but I haven't really dug into it yet.  I was thinking all themes to be separate.  For testing, I think git has a submodules feature, similar to SVN externals that might be the way to go.  More research is required.

**Comment by Engelbert** [comment]
If the size of it is in the core, we should take it out of the core and put it in the themes. Hard coded stuff like that is bound to break with different themes. I'll have a look and dig into it.
