### ISSUE TITLE
Ticket list is not Rendering properly

### ISSUE THREAD

**Issue by mdkaleel** [Project-Pier/ProjectPier-Core#18]
Ticket list is not Rendering properly
![pp_ticket](https://cloud.githubusercontent.com/assets/10484071/5699177/3de22a80-9a32-11e4-82c9-06a924c4686a.png)

**Comment by Engelbert** [comment]
This is a theme related issue, can you create this issue in the [ProjectPier-Theme-Marine](https://github.com/Project-Pier/ProjectPier-Theme-Marine) repo? (I can recreate/move the issue but you would not be updated on future developments)

Just folow this link: https://github.com/Project-Pier/ProjectPier-Theme-Marine/issues

can you also give me some more info on what browser, screenresolution, ...   you are using? Thanks in advance!

Thanks for reporting things like this!
