### ISSUE TITLE
Tasks PDF report revamped

### ISSUE THREAD

**Issue by Engelbert** [Project-Pier/ProjectPier-Core#19]
The tasks PDF report was not looking too bad. But IMO it could be better and easier to read.
Below you can find a screenshot, I could use some comments, remarks, tips on this one.
![screenshot from 2015-01-14 16 42 39](https://cloud.githubusercontent.com/assets/755439/5741617/7f8496ae-9c0c-11e4-8a17-604b522b8958.png)
I have all the working code on my testserver so if you :+1: it I can make a Pull request in no time :smile:

**Comment by JonDeG** [comment]
I think it looks really good!  Only feedback I can think of is to check how it works when spanning multiple pages and whether the name is the "username" or "display name". I think it should be "display name" if it isn't already.

**Comment by Engelbert** [comment]
Name displayed for the user is: 
```php
$task_assignee = $task->getAssignedTo()->getObjectName();
```

Spanning multiple pages is kind of hard to do proper. For now the cells with the info rollover just fine, but the cell with the description breaks into two pieces and does not roll to the next page. I'll post a screenie later today.

The footer is the same for every PDF report.
